version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AlexResumeChallenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19m153yz4044w"
s3_prefix = "AlexResumeChallenge"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

